# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Shoe.create!([
  {title: "NMD R1 PK 'JAPAN BOOST'", category: "Sneaker", brand: "Adidas", sex: 'unisex', description: "A breakthrough design, these shoes merge streetwise style and the latest adidas technologies. They feature a boost™ midsole for a sporty element, while the sleek, monochromatic look showcases a seamless and snug adidas Primeknit upper. EVA midsole plugs complete the NMD look.", color:"White, white, white", rating: 5},
  {title: "YEEZY BOOST 350 V2 'ZEBRA'", category: "Sneaker", brand: "Adidas", sex: 'unisex', description:"The adidas Yeezy 350 Boost is a low-top sneaker designed by Kanye West. The shoes first debuted at the YEEZY Season fashion show in February 2015 and new colorways were unveiled during YEEZY Season 3 on February 11th, 2016. The retail price for the shoe is $200 for the original and $220 for the V2. The latest “Semi-Frozen Yellow” colorway releases on November 18th, 2017, followed by the “Beluga 2.0” and “Blue Tint” colorways in December 2017.", color: "White, cblack, red", rating: 5},
  {title: "AIR JORDAN 1 RETRO HIGH OG YING YANG PACK", category: "Sneaker", brand: "Nike", sex: 'male', description:"Both pairs of the Air Jordan 1 used come in a simple theme which is flipped on each pair. While many are calling this the ‘Yin Yang’ Pack, the naming is not official at the time of writing. Breaking each pair down, the first Air Jordan 1 High OG comes in predominate Black on the uppers with White on the Swoosh, midsole, Wings branding and Nike Air while Red lands on the backdrop. The second comes in mainly White with Black on the Swoosh, Wings and liner and is completed with Red on the tongue tag.", rating: 5},
  {title: "MEN’S RADFORD 6-INCH BOOT YELLOW", category: "Boot", brand: "Timberland", sex: 'male', description: "STAY FLEXIBLE Tame uneven terrain with our SensorFlex™ technology, providing your feet with constant support, active cushioning and dynamic flex.
  LIGHTWEIGHT These may look like classic 6-inch boots, but they’re amazingly lightweight for even more comfort. PREMIUM WATERPROOF LEATHER We use the finest quality full-grain nubuck and thoroughly seal every seam for guaranteed waterproof performance..", color: "Wheat Waterbuck", rating: 5},
  {title: "AUTHENTIC 44 DX", category:"Skate", brand:"Vans", sex:'male', description:"Vans are a staple in skate culture and street style and the Vans Classic Slip-On are no exception. Functional and effortless in design, not to mention super easy to get on. Kick back in these slip-on sneakers on any day of the week. Simple.", color:"Black and White Checker/White", rating: 5},
  {title: "KOBE 10 ELITE LOW XMAS 'CHRISTMAS' ", category: "Basketball", brand:'male', sex: 0, description:"The Nike Kobe 10 Elite Low ‘Christmas’ is one of four pairs equaling the 2015 Nike Basketball ‘Christmas’ pack inspired by fire and ice that will release towards the end of December. The Kobe 10 edition is apart of the fire series and goes a bit deeper than the other models. Using a bright crimson Flyknit upper to represent fire while the lateral side is done in black. The two shades then mix it up on the toe box. Following is metallic gold landing on the swoosh, tongue branding and the five championship rings on the heel. The last detail is a compass with a basketball and his number 24 on the inside of the tongue.", color:"black, mtllc gold-brght cxrmnsn ", rating: 5},
  {title: "4Nite", category:"Sandal", brand:"Havaianas Australia", sex: 'male', description:"Havaianas 4Nite Black/Black/Fosforescent Thongs. Charge all day and glow all night in Havaianas 4Nite. Classic white Havaianas featuring a glow in the dark wolf print on the sole with matching black top straps and a contrasting fluro rubber logo. Havaianas flip flops are made from premium quality Brazilian rubber. All thongs come with our 6 month quality guarantee.", color:"Black, Black, Phosphorescent", rating: 5},
  {title: "DARCY FLORAL PASCAL", category:"Boot", brand:"Dr. Martin", sex: 'unisex', description:"Darcy Floral, a circa-90s print from our archives, is reinvigorated with rich, multi-colored blooms against a black leather background. With a soft, hand-painted effect, the pattern effortlessly brings floral from summer to fall — but it's the boot's tough femininity that we love the most. The women's 8-eye Pascal has all the traditional Doc's DNA, like grooved edges, yellow stitching and the classic heel-loop. Built to last, it's made using one of the finest methods of construction: the Goodyear Welt — which means the upper and sole are sewn together in our heat-sealed z-welt stitch. The boot sits on our durable, comfortable AirWair™ sole, that's oil and fat resistant with good abrasion and slip resistance.", color:"Black, floral", rating: 5}
])